name: API Gateway CI

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - 'services/api/**'
  push:
    branches: [ "main" ]
    paths:
      - 'services/api/**'

jobs:
  test-api:
    name: Lint and Test API
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Just
        uses: extractions/setup-just@v2

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: uv sync --frozen

      - name: Cache Mypy
        uses: actions/cache@v4
        with:
          path: .mypy_cache
          key: mypy-${{ runner.os }}-${{ hashFiles('uv.lock') }}
          restore-keys: |
            mypy-${{ runner.os }}-

      - name: Run CI Checks
        run: just ci-check api_gateway

      # - name: Run Tests
      #   run: just test api_gateway